//----------------------------------------------
// Auto-generated file - DO NOT EDIT
// Generated by increment_build.cmake
//----------------------------------------------

#pragma once

#define FIRMWARE_BUILD_NUMBER 183
#define FIRMWARE_BUILD_STRING "183"
