//----------------------------------------------
// Auto-generated file - DO NOT EDIT
// Generated by increment_build.cmake
//----------------------------------------------

#pragma once

#define FIRMWARE_BUILD_NUMBER 202
#define FIRMWARE_BUILD_STRING "202"
