//----------------------------------------------
// Auto-generated file - DO NOT EDIT
// Generated by increment_build.sh
//----------------------------------------------

#pragma once

#define FIRMWARE_BUILD_NUMBER 1
#define FIRMWARE_BUILD_STRING "1"
