#!/bin/bash
# Increment build number for Heltec Flight Computer firmware

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_FILE="$SCRIPT_DIR/build_number.txt"
HEADER_FILE="$SCRIPT_DIR/build_number.h"

# Read current build number
if [ -f "$BUILD_FILE" ]; then
    BUILD_NUM=$(cat "$BUILD_FILE")
else
    BUILD_NUM=0
fi

# Increment
BUILD_NUM=$((BUILD_NUM + 1))

# Write back
echo "$BUILD_NUM" > "$BUILD_FILE"

# Generate header file
cat > "$HEADER_FILE" << EOF
//----------------------------------------------
// Auto-generated file - DO NOT EDIT
// Generated by increment_build.sh
//----------------------------------------------

#pragma once

#define FIRMWARE_BUILD_NUMBER $BUILD_NUM
#define FIRMWARE_BUILD_STRING "$BUILD_NUM"
EOF

echo "Build number incremented to $BUILD_NUM"
