# increment_build.cmake
# Reads build number from file, increments it, writes back, and generates header

set(BUILD_NUMBER_FILE "${CMAKE_CURRENT_LIST_DIR}/build_number.txt")
set(BUILD_HEADER_FILE "${CMAKE_CURRENT_LIST_DIR}/include/build_number.h")

# Read current build number
if(EXISTS "${BUILD_NUMBER_FILE}")
    file(READ "${BUILD_NUMBER_FILE}" BUILD_NUMBER)
    string(STRIP "${BUILD_NUMBER}" BUILD_NUMBER)
else()
    set(BUILD_NUMBER 0)
endif()

# Increment build number
math(EXPR BUILD_NUMBER "${BUILD_NUMBER} + 1")

# Write new build number back to file
file(WRITE "${BUILD_NUMBER_FILE}" "${BUILD_NUMBER}\n")

# Generate header file
file(WRITE "${BUILD_HEADER_FILE}"
"//----------------------------------------------
// Auto-generated file - DO NOT EDIT
// Generated by increment_build.cmake
//----------------------------------------------

#pragma once

#define FIRMWARE_BUILD_NUMBER ${BUILD_NUMBER}
#define FIRMWARE_BUILD_STRING \"${BUILD_NUMBER}\"
")

message(STATUS "Build number: ${BUILD_NUMBER}")
