//----------------------------------------------
// Auto-generated file - DO NOT EDIT
// Generated by increment_build.sh
//----------------------------------------------

#pragma once

#define FIRMWARE_BUILD_NUMBER 16
#define FIRMWARE_BUILD_STRING "16"
