#!/bin/bash
# increment_build.sh
# Reads build number from file, increments it, writes back, and generates header

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_NUMBER_FILE="${SCRIPT_DIR}/build_number.txt"
BUILD_HEADER_FILE="${SCRIPT_DIR}/build_number.h"

# Read current build number
if [ -f "${BUILD_NUMBER_FILE}" ]; then
    BUILD_NUMBER=$(cat "${BUILD_NUMBER_FILE}" | tr -d '[:space:]')
else
    BUILD_NUMBER=0
fi

# Increment build number
BUILD_NUMBER=$((BUILD_NUMBER + 1))

# Write new build number back to file
echo "${BUILD_NUMBER}" > "${BUILD_NUMBER_FILE}"

# Generate header file
cat > "${BUILD_HEADER_FILE}" << EOF
//----------------------------------------------
// Auto-generated file - DO NOT EDIT
// Generated by increment_build.sh
//----------------------------------------------

#pragma once

#define FIRMWARE_BUILD_NUMBER ${BUILD_NUMBER}
#define FIRMWARE_BUILD_STRING "${BUILD_NUMBER}"
EOF

echo "Build number: ${BUILD_NUMBER}"
