//----------------------------------------------
// Module: version.h
// Description: Firmware version information
//   for Heltec Wireless Tracker Gateway
// Author: Mark Gavin
// Created: 2026-01-17
// Modified: 2026-01-31 (Switched to auto-incrementing build number)
// Copyright: (c) 2025-2026 by Mark Gavin
// License: Proprietary - All Rights Reserved
//----------------------------------------------

#pragma once

#include "build_number.h"

//----------------------------------------------
// Firmware Identification
//----------------------------------------------
#define FIRMWARE_NAME           "RocketAvionics"
#define FIRMWARE_TYPE           "HeltecGateway"

// Build number is auto-incremented on each build
// Defined in build_number.h (auto-generated by increment_build.sh)
#define FIRMWARE_VERSION_STRING "Build " FIRMWARE_BUILD_STRING

//----------------------------------------------
// Build Timestamp
// Arduino IDE rebuilds all files, so these are always current
//----------------------------------------------
#define FIRMWARE_BUILD_DATE         __DATE__
#define FIRMWARE_BUILD_TIME         __TIME__
